---
- name: Get Vector distrib
  ansible.builtin.get_url:
    url: "{{ vector_rpm }}"
    dest: "./vector-{{ vector_version }}.rpm"
  tags: vector
- name: Install vector packages
  become: true
  ansible.builtin.yum:
    name: vector-{{ vector_version }}.rpm
  tags: vector
- name: Copy config
  become: true
  template:
    src: templates/vector.yaml.j2
    dest: "{{ vector_config_dir }}/vector.yaml"
    validate: vector validate --no-environment --config-yaml %s
  tags: vector
- name: vector service
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
- name: start vector
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true

- name: Make log dir
  ansible.builtin.file:
    path: /media/logs
    state: directory
    mode: '0755'
- name: Make log file
  ansible.builtin.file:
    path: /media/logs/rsyslog.log
    state: touch
    mode: '0755'
- name: Install rsyslog
  become: true
  ansible.builtin.yum:
    name: rsyslog
  notify: start_rsyslog
- name: copy rsyslog config
  become: true
  copy:
    src: files/rsyslog.conf
    dest: /etc/rsyslog.conf
  notify: start_rsyslog
